name = 'NgeBlog'
license = 'MIT'
licenselink = 'https://github.com/rebelsec/NgeBlog/blob/main/LICENSE'
description = 'a Minimalist , clean, and elegant blog theme for Hugo.'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/rebelsec/NgeBlog'

# If you have a running demo of the theme
demosite = 'https:///www.rebelsec.github.io/'

# Taxonomy terms
tags = ['blog', 'dark', 'light', 'minimal', 'responsive', 'personal']
features = ['Optimized SEO', 'Desktop/Mobile Responsive layout', 'Light/Dark mode', 'Pagination supported', 'Easy-to-use and self-expanding table of contents', 'Tailwind CSS']

# If the theme has a single author
[author]
  name = 'Galatia Sijabat'
  homepage = 'https://www.rebelsec.id/'
